# Generated by Django 3.2.5 on 2021-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=20)),
                ('stuemail', models.EmailField(max_length=40)),
                ('stupass', models.CharField(max_length=40)),
                ('stumarks', models.IntegerField(null=True)),
                ('stuavg', models.IntegerField(default=True)),
                ('stupercent', models.IntegerField(blank=True)),
            ],
        ),
    ]
