# Generated by Django 3.2.5 on 2021-07-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterModelTable',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allapp.student')),
            ],
            bases=('allapp.student',),
        ),
    ]
