# Generated by Django 3.2.5 on 2021-07-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0002_altermodeltable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='altermodeltable',
            table='empname',
        ),
    ]
