# Generated by Django 3.2.5 on 2021-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GstRegistration',
            fields=[
                ('Invoice_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Customer_Address', models.CharField(max_length=50)),
                ('Customer_Mobile_Number', models.IntegerField()),
                ('Customer_GST', models.IntegerField()),
            ],
        ),
    ]
