# Generated by Django 3.2.5 on 2021-08-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstregistration',
            name='Vehicle_Number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
