# Generated by Django 3.2.5 on 2021-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstapp', '0002_gstregistration_vehicle_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstregistration',
            old_name='Customer_GST',
            new_name='GST',
        ),
        migrations.RenameField(
            model_name='gstregistration',
            old_name='Vehicle_Number',
            new_name='Total',
        ),
        migrations.AddField(
            model_name='gstregistration',
            name='Product',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
