# Generated by Django 3.2.5 on 2021-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstapp', '0003_auto_20210802_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstregistration',
            name='Product_Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
