# Generated by Django 3.2.5 on 2021-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stdpass',
            new_name='password',
        ),
    ]
